# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100, verbose_name='标题')),
                ('pub_time', models.CharField(db_column='pub_time', max_length=100, verbose_name='发表时间')),
                ('url', models.CharField(db_column='url', max_length=255, verbose_name='链接')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
                ('kinds', models.CharField(db_column='kinds', max_length=32, verbose_name='种类')),
            ],
            options={
                'verbose_name_plural': '新闻',
                'db_table': 'news',
            },
        ),
    ]
